# Generated by Django 3.1.7 on 2021-02-25 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_gusto', '0004_auto_20210225_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user_massage',
            new_name='user_message',
        ),
    ]
